### ISSUE TITLE
SMETH 18 - Add stakeholders not spoken to issue summary

### ISSUE THREAD

**Issue by SahityaRaipura** [david-fisher/320-S21-Track1#233]
Every stakeholder has a summary of what they would say about each issue. We can add this in the point selection feature in the editor.

After the student picks stakeholders to talk to in the scenario (in the simulator), in the summary at the end we display the summary of what the stakeholders they didn't speak to had to say about each issue.

**Comment by Enoch-Hsiao** [comment]
This is done on the editor side, this is not done on the simulator side yet
