### ISSUE TITLE
No errors when starting docker, but cannot access localhost:300x pages [ERR_EMPTY_RESPONSE]

### ISSUE THREAD

**Issue by jackwilliams2480** [david-fisher/320-S21-Track1#79]
I attached my terminal output when running docker-compose up. I assume the 0.0.0.0 is not the error. I am running on windows 10 and followed all the requirements for docker desktop, the ubuntu vm, wsl 2, ... 
This error started a few days ago when I hadn't changed anything. I have tried fresh installing main and docker desktop but still get the error. 

[consoletext.txt](https://github.com/david-fisher/320-S21-Track1/files/6273771/consoletext.txt)

**Comment by bunny0310** [comment]
You're gonna have to ensure you have latest version of requirements.txt before you do docker-compose up. Those errors stem from the fact that all the required dependencies have not been installed inside of the container. I guess python doesn't automatically update the requirements.txt file whenever you install a new dependency, so you guys have to do that manually. Just ensure that your requirements.txt file is always up to date. Once you update the requirements.txt file and then docker-compose up, it should work just fine. Hope this helps!

**Comment by adamlechowicz** [comment]
A couple people on my superteam (Django Fett-T7) are having this same issue after a fresh clone from main.  Docker works great, everything spins up correctly, but the React apps are not accessible through the browser at "localhost:300x".  The React apps ARE accessible if we run them directly without using Docker (npm start), they just do not give a response when running in Docker Desktop.  Not everyone is having this issue with the latest version of main, but many of us are having these same symptoms.

**Comment by bunny0310** [comment]
@adamlechowicz can you paste the log output here? You can find it by running _**docker logs frontend**_ in a new terminal window while the containers are up or you could also type that in the same terminal window if you used _**docker-compose up -d**_ to spin up the containers.

**Comment by jenozin** [comment]
The outputs are just frontend warnings like no-unused-vars. But when we try to open the apps in the browser we get "localhost didn’t send any data."
